% scriptexample - example file for running the ADCP toolbox in automated mode


%%% START USGS BOILERPLATE -------------%
% Use of this program is described in:
%
% Acoustic Doppler Current Profiler Data Processing System Manual 
% Jessica M. Côté, Frances A. Hotchkiss, Marinna Martini, Charles R. Denham
% Revisions by: Andrée L. Ramsey, Stephen Ruane
% U.S. Geological Survey Open File Report 00-458 
% Check for later versions of this Open-File, it is a living document.
%
% Program written in Matlab v7.1.0 SP3
% Program updated in Matlab 7.2.0.232 (R2006a)
% Program ran on PC with Windows XP Professional OS.
%
% "Although this program has been used by the USGS, no warranty, 
% expressed or implied, is made by the USGS or the United States 
% Government as to the accuracy and functioning of the program 
% and related program material nor shall the fact of distribution 
% constitute any such warranty, and no responsibility is assumed 
% by the USGS in connection therewith."
%
%%% END USGS BOILERPLATE --------------

 
% --------- set up the information needed by the programs
%
% metadata for mooring 8221
settings.numRawFile = 1; % number of raw binary ADCP files (*.000 or *.PD0), max = 2
settings.rawdata1 = '8221WHpart1.000'; % raw file #1
settings.rawdata2 = ''; % raw file #2, if any
settings.rawcdf = '8221wh.cdf'; % output file name for the raw data in netCDF format
settings.theFilledFile = '8221whF.cdf'; % the name of the fill file
settings.theMaskFile = '8221wh.msk'; % the name of the mask file
settings.theNewADCPFile = '8221whM.cdf'; % the name of the new file with the mask applied
settings.trimFile = '8221whT.cdf'; % the name of the file trimmed by time out of water and by bin
settings.rdi2cdf.run = 1; % force runadcp to run rdi2cdf (future implementation)
settings.rdi2cdf.Mooring_number = '8221'; % mooring number (USGS) or other identifier
settings.rdi2cdf.Deployment_date = '28-jun-2006';  % date the ADCP entered the water
settings.rdi2cdf.Recovery_date = '19-sep-2006'; % date the ADCP exited the water
settings.water_depth = 20.5; % in meters
settings.rdi2cdf.ADCP_serial_number = 2054; 
settings.rdi2cdf.xducer_offset = 1.235; % ADCP transducer offset from the sea bed
settings.rdi2cdf.pred_accuracy = 0.79; % from TRDI PLAN in cm/s
settings.rdi2cdf.slow_by = 3*60+9; % clock drift
settings.rdi2cdf.magnetic = 12.9; % declination in degrees, west is negative
settings.fixens.run = 1; % force runadcp to run fixens (future implementation)
settings.runmask.noninteractive = 1; % don't bring up starbare in runmask 
% use this to override goodends' search for tripod tilt, etc.
% use it if you are really running in batch and don't want goodends to prompt you
settings.goodends.stop_date = settings.rdi2cdf.Recovery_date; % set to [] to disable
settings.trimbins.numRawFile = settings.numRawFile; % leave this alone
settings.trimbins.rawdata1 = settings.rawdata1; % leave this alone
settings.trimbins.rawdata2 = settings.rawdata2; % leave this alone
settings.trimbins.trimFile = settings.trimFile; % leave this alone
% method to remove bins above the surface (see trimbins documentation
settings.trimbins.method = 'Pressure Sensor'; %'RDI Surface Program' | 'User Input'
% percent of water column to make sure is preserved when trimming (1 = 100%)
settings.trimbins.percentwc = 1.12; % to capture full range of tide
settings.trimbins.ADCP_offset = settings.rdi2cdf.xducer_offset; % leave this alone
% path to the TRDI surface program, if you are on a PC
% we have permission to distribute TRDI's surface.exe with the toolbox
% so this should be your toolbox path, Demo directory
settings.trimbins.progPath = 'C:\mfiles\m_cmg\adcp_tbx\trunk\AddOns'; % or ''
settings.adcp2ep.epDataFile = '8221wh.nc'; % final output file name
settings.adcp2ep.experiment = 'Huntington Beach, summer 2006'; % your metadata
settings.adcp2ep.project = 'Coastal and Marine Geology Program, Circulation and Sediment transport'; % your metadata
settings.adcp2ep.descript = 'HB06'; % your metadata, station or site number, for example
settings.adcp2ep.SciPi = 'Noble'; % your metadata, principal investigator
settings.adcp2ep.cmnt = 'HB06 Site MF Micropod Deployment 1';  % your metadata
settings.adcp2ep.water_mass = ' '; % an EPIC requirement
settings.adcp2ep.long = 117.977474; % always positive degrees
settings.adcp2ep.lonUnits = 'degrees_west';
settings.adcp2ep.latit = 33.629065; % always positive degrees
settings.adcp2ep.latUnits = 'degrees_north';
% the dialog file for your ADCP, there is one in the Demo directory.
% the toolbox use the instrument elevation and azimuth specific to each ADCP
settings.adcp2ep.dlgFile = '822wh.dlg'; % generated by the ADCP using the PS3 command
settings.adcp2ep.ADCPtype = 'WH'; % workhorse or BB for broadband

% --------------------- run the programs
%
% turn each step "on" and "off" by setting "if 0" to "if 1"
% steps must be run in sequence

diary(sprintf('run%s',datestr(now, 30)))

% sometimes ADCPs don't know which way they were really facing.
% only for deployments that need orientation fixed, implement the following:
if 0, % run rdi2cdf separately to fix the orientation
    rdi2cdf(settings.rawdata1,settings.rawcdf,[],[],...
        settings.rdi2cdf); % user's provideing metadata
    orientation = 'UP'; % 'UP' or 'DOWN'
    fixorientation(settings.rawcdf,orientation);
    % when rdi2cdf is run the second time via runadcp (below) 
    % the file converted here will not be overwritten
end

if 0, % translate to netcdf, mask for basic errors and trim the data
    runadcp(settings)
end

if 0, % apply a mask that tracks the surface - if you wish to
    [path, name, ext] = fileparts(settings.trimFile);
    theMaskFile = fullfile(path,[name, '.msk']);
    theNewADCPFile = fullfile(path,[name, 'P.cdf']);
    [theNewADCPFile, theMaskFile] = pressuremask (settings.trimFile,...
        theMaskFile,theNewADCPFile)
end

if 1, % rotate from beam to earth coordinates, translate raw netCDF to EPIC
    [path, name, ext] = fileparts(settings.trimFile);
    theNewADCPFile = fullfile(path,[name, 'P.cdf']);
    if exist(theNewADCPFile,'file'),
        settings.trimFile = theNewADCPFile;
        disp(['Using ',settings.trimFile,' for adcp2ep'])
    end
    adcp2ep(settings.trimFile, settings.adcp2ep.epDataFile, ...
        settings.adcp2ep.ADCPtype, settings.adcp2ep.dlgFile, settings.adcp2ep)
end

diary off
